version: 0.0.{build}

branches:
# whitelist
    only:
        - master
        - appveyor

install:
    - git submodule -q update --init

before_build:
    - mkdir build
    - cmake -G"Visual Studio 12" -T v120 .\ -B.\build

build:
    project: build\rxcpp.sln
